---
- hosts: all
  tasks:
  - name: Ensure nginx is at the latest version
    apt: name=nginx state=latest
    become: true
  - name: start nginx
    become: true
    service:
        name: nginx
        state: started
  - name: Install prerequisites
    apt: name={{item}} update_cache=yes
    become: true
    with_items:
     - apt-transport-https
     - ca-certificates
     - curl
     - software-properties-common
  - name: Add Docker GPG key
    become: true
    apt_key: url=https://download.docker.com/linux/ubuntu/gpg
  - name: Add Docker APT repository
    become: true
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
  - name: Install Docker
    become: true
    apt: name=docker-ce state=latest  